import { MyHeader } from '@/components/MyHeader/MyHeader';
import './globals.css';

export const metadata = {
  title: 'Сервис B+',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/tt-wellingtons-trl"
          rel="stylesheet"
        />
      </head>
      <body>
        <MyHeader />
        <main>{children}</main>
      </body>
    </html>
  );
}
