import { MyHeader } from '@/components/MyHeader/MyHeader';
import './globals.css';
import localFont from 'next/font/local';

const wellingtons = localFont({
  src: [
    {
      path: '../public/fonts/TTWellingtons-ExtraBold.woff2',
      weight: '800',
    },
    {
      path: '../public/fonts/TTWellingtons-Regular.woff2',
      weight: '400',
    },
  ],
});

export const metadata = {
  title: 'Сервис B+',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={wellingtons.className}>
      <body>
        <MyHeader />
        <main>{children}</main>
      </body>
    </html>
  );
}
